# workflow/Snakefile
import os
import yaml

CONFIG_PATH = os.environ.get("CONFIG_PATH", "config/run_config.yaml")
configfile: CONFIG_PATH


IP_REPS = list(config["samples"]["ip"].keys())

rule all:
    input:
        "results/PureCLIP.crosslink_sites.bed",
        "results/PureCLIP.binding_regions.bed",
        "results/binding_sites.reproducible.bed",
        expand("results/ip_{rep}/pureclip_sites.bed", rep=IP_REPS),
        "results/score_report.json"

rule merge_ip:
    input:
        [config["samples"]["ip"][rep]["bam"] for rep in IP_REPS]
    output:
        bam="results/merged_ip.bam",
        bai="results/merged_ip.bam.bai"
    log:
        "results/logs/merge_ip.log"
    shell:
        """
        echo "[merge_ip] inputs={input}" > {log}
        samtools merge -f {output.bam} {input} >> {log} 2>&1
        samtools index {output.bam} >> {log} 2>&1
        """

rule pureclip:
    input:
        bam="results/merged_ip.bam",
        bai="results/merged_ip.bam.bai",
        genome=config["reference"]["genome_fasta"],
        input_bam=config["samples"]["input_control"]["rep1"]["bam"] if config["pureclip"]["use_input_covariate"] else [],
        input_bai=config["samples"]["input_control"]["rep1"]["bam"] + ".bai" if config["pureclip"]["use_input_covariate"] else []
    output:
        sites="results/PureCLIP.crosslink_sites.bed",
        regions="results/PureCLIP.binding_regions.bed"
    params:
        bw=config["pureclip"]["bandwidth_nt"],
        dm=config["pureclip"]["merge_distance_nt"],
        ld="-ld" if config["pureclip"]["high_precision_mode"] else "",
        ibam=(f"-ibam {config['samples']['input_control']['rep1']['bam']} "
              f"-ibai {config['samples']['input_control']['rep1']['bam']}.bai"
              if config["pureclip"]["use_input_covariate"] else "")
    threads: config["resources"]["threads"]
    log:
        "results/logs/pureclip_merged.log"
    shell:
        """
        echo "[pureclip merged] bw={params.bw} dm={params.dm} ld='{params.ld}'" > {log}
        pureclip \
            -i {input.bam} \
            -bai {input.bam}.bai \
            -g {input.genome} \
            -nt {threads} \
            -bw {params.bw} \
            -dm {params.dm} \
            {params.ld} \
            {params.ibam} \
            -o {output.sites} \
            -or {output.regions} >> {log} 2>&1
        """

rule pureclip_per_replicate:
    input:
        bam=lambda wildcards: config["samples"]["ip"][wildcards.rep]["bam"],
        bai=lambda wildcards: config["samples"]["ip"][wildcards.rep]["bam"] + ".bai",
        genome=config["reference"]["genome_fasta"],
        input_bam=config["samples"]["input_control"]["rep1"]["bam"] if config["pureclip"]["use_input_covariate"] else [],
        input_bai=config["samples"]["input_control"]["rep1"]["bam"] + ".bai" if config["pureclip"]["use_input_covariate"] else []
    output:
        sites="results/ip_{rep}/pureclip_sites.bed",
        regions="results/ip_{rep}/pureclip_regions.bed"
    params:
        bw=config["pureclip"]["bandwidth_nt"],
        dm=config["pureclip"]["merge_distance_nt"],
        ld="-ld" if config["pureclip"]["high_precision_mode"] else "",
        ibam=(f"-ibam {config['samples']['input_control']['rep1']['bam']} "
              f"-ibai {config['samples']['input_control']['rep1']['bam']}.bai"
              if config["pureclip"]["use_input_covariate"] else "")
    threads: config["resources"]["threads"]
    log:
        "results/ip_{rep}/logs/pureclip.log"
    shell:
        """
        echo "[pureclip per-rep] rep={wildcards.rep} bw={params.bw} dm={params.dm}" > {log}
        pureclip \
            -i {input.bam} \
            -bai {input.bai} \
            -g {input.genome} \
            -nt {threads} \
            -bw {params.bw} \
            -dm {params.dm} \
            {params.ld} \
            {params.ibam} \
            -o {output.sites} \
            -or {output.regions} >> {log} 2>&1
        """

rule postprocess:
    input:
        regions="results/PureCLIP.binding_regions.bed",
        sites="results/PureCLIP.crosslink_sites.bed"
    output:
        bed="results/binding_sites.reproducible.bed"
    params:
        config_path=CONFIG_PATH
    log:
        "results/logs/postprocess.log"
    shell:
        "PYTHONPATH=. python workflow/postprocess.py {params.config_path} {output.bed} 2>&1 | tee {log}"

rule score:
    input:
        merged_sites="results/binding_sites.reproducible.bed",
        rep_regions=expand("results/ip_{rep}/pureclip_regions.bed", rep=IP_REPS)
    output:
        report="results/score_report.json"
    params:
        config_path=CONFIG_PATH
    log:
        "results/logs/score.log"
    shell:
        "PYTHONPATH=. python scorers/run_scorers.py {params.config_path} {output.report} > {log} 2>&1"
