import yaml
import pytest
from agent.report import main
import sys
from unittest.mock import patch

@pytest.fixture
def mock_report_data(tmp_path):
    # Create mock results dir
    results_dir = tmp_path / "results_mock"
    results_dir.mkdir()
    
    # Create mock history.jsonl
    history_file = results_dir / "mock_config_history.jsonl"
    with open(history_file, "w", encoding="utf-8") as f:
        f.write('{"iteration": 0, "config": {"pureclip": {"bandwidth_nt": 50}}, "scores": {"replicate_agreement": 0.5, "n_binding_sites": 100, "motif_hit_rate": null, "mean_sbr": null}, "objective_metric": "replicate_agreement"}\n')
        f.write('{"iteration": 1, "config": {"pureclip": {"bandwidth_nt": 60}}, "scores": {"replicate_agreement": 0.6, "n_binding_sites": 90, "motif_hit_rate": 0.8, "mean_sbr": null}, "objective_metric": "replicate_agreement"}\n')
        f.write('{"iteration": 2, "config": {"pureclip": {"bandwidth_nt": 70}}, "scores": {"replicate_agreement": 0.7, "n_binding_sites": 80, "motif_hit_rate": 0.9, "mean_sbr": null}, "objective_metric": "replicate_agreement"}\n')
        
    # Create mock config
    config_file = tmp_path / "mock_config.yaml"
    config_data = {
        "run_id": "TEST_ITER",
        "dataset_id": "TEST_DATASET",
        "target_protein": "TEST_PROT",
        "cell_line": "TEST_CELL",
        "priors": {
            "known_motifs": [{"pattern": "UGCAUG", "type": "target"}]
        },
        "output": {
            "results_root": str(results_dir),
            "results_dir": str(results_dir)
        }
    }
    with open(config_file, "w", encoding="utf-8") as f:
        yaml.dump(config_data, f)
        
    return config_file

def test_generate_report_html_fallback(mock_report_data, tmp_path):
    output_pdf = tmp_path / "report_test.pdf"
    
    # Mock sys.argv
    test_args = ["report.py", str(mock_report_data), str(output_pdf)]
    
    # Patch weasyprint so it always falls back to HTML for testing logic locally
    # Also patch the Gemini LLM call to avoid real API usage during testing
    with patch.dict('sys.modules', {'weasyprint': None}):
        with patch('langchain_google_genai.ChatGoogleGenerativeAI') as MockLLM:
            mock_instance = MockLLM.return_value
            mock_instance.invoke.return_value.content = "⚠️ This test report was automatically generated by Pytest and does not include a real Gemini API call (Gemini API is mocked during testing)."
            with patch.object(sys, 'argv', test_args):
                main()
                
    output_html = tmp_path / "report_test.html"
    assert output_html.exists()
    
    content = output_html.read_text(encoding="utf-8")
    assert "TEST_PROT" in content
    assert "TEST_CELL" in content
    assert "replicate_agreement" in content
    # Check null handling fallback
    assert "N/A" in content
    
    # Best iteration (highest replicate_agreement = 0.7) should be iter 2
    assert 'class="best-row"' in content
    assert "bandwidth_nt: 70" in content
    assert "0.7" in content
    assert "#2" in content
    
    # Chart should be generated
    assert "data:image/png;base64" in content
    
    # Check that LLM was mocked
    assert "Gemini API is mocked during testing" in content

def test_generate_report_html_fallback_under_3_iterations(tmp_path):
    # Create mock results dir
    results_dir = tmp_path / "results_mock"
    results_dir.mkdir()
    
    # Create mock history.jsonl with only 2 iterations
    history_file = results_dir / "mock_config_2_iters_history.jsonl"
    with open(history_file, "w", encoding="utf-8") as f:
        f.write('{"iteration": 0, "config": {"pureclip": {"bandwidth_nt": 50}}, "scores": {"replicate_agreement": 0.5, "n_binding_sites": 100}, "objective_metric": "replicate_agreement"}\n')
        f.write('{"iteration": 1, "config": {"pureclip": {"bandwidth_nt": 60}}, "scores": {"replicate_agreement": 0.6, "n_binding_sites": 90}, "objective_metric": "replicate_agreement"}\n')
        
    config_file = tmp_path / "mock_config_2_iters.yaml"
    config_data = {
        "run_id": "TEST_ITER",
        "target_protein": "TEST_PROT",
        "cell_line": "TEST_CELL",
        "output": {
            "results_root": str(results_dir),
            "results_dir": str(results_dir)
        }
    }
    with open(config_file, "w", encoding="utf-8") as f:
        yaml.dump(config_data, f)
        
    output_pdf = tmp_path / "report_test_2.pdf"
    test_args = ["report.py", str(config_file), str(output_pdf)]
    
    with patch.dict('sys.modules', {'weasyprint': None}):
        with patch('langchain_google_genai.ChatGoogleGenerativeAI') as MockLLM:
            mock_instance = MockLLM.return_value
            mock_instance.invoke.return_value.content = "Mocked LLM output."
            with patch.object(sys, 'argv', test_args):
                main()
            
    output_html = tmp_path / "report_test_2.html"
    assert output_html.exists()
    
    content = output_html.read_text(encoding="utf-8")
    assert "Not enough iterations to generate a trend chart" in content
    assert "data:image/png;base64" not in content
