run_id: HNRNPM_K562_iter_00
dataset_id: HNRNPM_K562
target_protein: HNRNPM
cell_line: K562
clip_protocol: eCLIP
samples:
  ip:
    rep1:
      bam: data/HNRNPM_K562/bam/ip_rep1_v1/ENCFF050PTL.bam
    rep2:
      bam: data/HNRNPM_K562/bam/ip_rep2_v1/ENCFF379LZD.bam
  input_control:
    rep1:
      bam: data/HNRNPM_K562/bam/smi_v1/ENCFF532ADX.bam
reference:
  genome_fasta: data/GRCh38.primary_assembly.genome.fa/GRCh38.primary_assembly.genome.fa
  annotation_gtf: null
priors:
  target_protein: HNRNPM
  clip_protocol: eCLIP
  expected_footprint_width_nt: 9
  known_motifs:
  - pattern: TTTTGTGGCTG
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.0
    consensus: TTTTGTGGCTG
  - pattern: TTCTGTGGTGT
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.1
    consensus: TTCTGTGGTGT
  - pattern: TTTGTGGCTGT
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.2
    consensus: TTTGTGGCTGT
  - pattern: TTTGTGGTCTG
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.3
    consensus: TTTGTGGTCTG
  - pattern: TTCTTGGTGGT
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.4
    consensus: TTCTTGGTGGT
  - pattern: TTCTGGTGTGG
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.5
    consensus: TTCTGGTGTGG
  - pattern: TTCGTGGTTTT
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.6
    consensus: TTCGTGGTTTT
  - pattern: TTGCTTGTGGG
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.7
    consensus: TTGCTTGTGGG
  - pattern: TTTTGGCTGGG
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.8
    consensus: TTTTGGCTGGG
  - pattern: TTTCTGGTGGG
    type: target
    source_database: mCrossBase
    motif_id: K562.HNRNPM.9
    consensus: TTTCTGGTGGG
  primary_objective_metric: replicate_agreement
pureclip:
  bandwidth_nt: 50
  merge_distance_nt: 8
  high_precision_mode: false
  use_input_covariate: true
  use_cl_motif_covariate: false
  cl_motif_file: null
postprocessing:
  force_width: 9
  cluster_gap_width: 8
  min_region_length_nt: 3
  min_crosslink_events: 3
reproducibility:
  percentile_threshold: 10
  min_crosslink_events_floor: 2
  min_replicates_passing: 2
benchmark:
  top_regions_bed: data/HNRNPM_K562/top_regions/regions.bed6
  top_crosslinks_bed: data/HNRNPM_K562/top_crosslink_sites/crosslinks.bed6
  top_genes: data/HNRNPM_K562/top_genes/list.txt
  biotypes_tsv: data/HNRNPM_K562/biotypes_genetypes/biotypes_proportions.tsv
  genotypes_tsv: data/HNRNPM_K562/biotypes_genetypes/genetypes_proportions.tsv
output:
  results_dir: results/datasets/HNRNPM_K562
resources:
  max_memory_gb: 16
  threads: 8
