clip_protocol: eCLIP
postprocessing:
  cluster_gap_width: 8
  force_width: 9
  min_crosslink_events: 6
  min_region_length_nt: 3
pureclip:
  bandwidth_nt: 50
  cl_motif_file: null
  high_precision_mode: false
  merge_distance_nt: 8
  use_cl_motif_covariate: false
  use_input_covariate: true
reference:
  annotation_gtf: ref/test_chr21.gtf
  genome_fasta: ref/test_chr21.fa
reproducibility:
  min_crosslink_events_floor: 2
  min_replicates_passing: 2
  percentile_threshold: 10
resources:
  max_memory_gb: 16
  threads: 8
run_id: RBFOX2_iter_09
samples:
  input_control:
    rep1:
      bam: results/input_control_rep1/dedup.bam
  ip:
    rep1:
      bam: results/ip_rep1/dedup.bam
    rep2:
      bam: results/ip_rep2/dedup.bam
target_protein: RBFOX2
