benchmark:
  biotypes_tsv: data/RBFOX2_K562/biotypes_genetypes/biotypes_proportions.tsv
  genotypes_tsv: data/RBFOX2_K562/biotypes_genetypes/genetypes_proportions.tsv
  top_crosslinks_bed: data/RBFOX2_K562/top_crosslink_sites/crosslinks.bed6
  top_genes: data/RBFOX2_K562/top_genes/list.txt
  top_regions_bed: data/RBFOX2_K562/top_regions/regions.bed6
cell_line: K562
clip_protocol: eCLIP
dataset_id: RBFOX2_K562
output:
  results_dir: results/runs/RBFOX2_iter_04
  results_root: results/runs
  use_run_id_subdir: true
postprocessing:
  cluster_gap_width: 8
  force_width: 9
  min_crosslink_events: 4
  min_region_length_nt: 3
priors:
  clip_protocol: eCLIP
  expected_footprint_width_nt: 9
  known_motifs:
  - consensus: TTTGCATGCTT
    motif_id: K562.RBFOX2.0
    pattern: TTTGCATGCTT
    source_database: mCrossBase
    type: target
  - consensus: TTGCATGCTTT
    motif_id: K562.RBFOX2.1
    pattern: TTGCATGCTTT
    source_database: mCrossBase
    type: target
  - consensus: GTATGCATGCT
    motif_id: K562.RBFOX2.2
    pattern: GTATGCATGCT
    source_database: mCrossBase
    type: target
  primary_objective_metric: replicate_agreement
  target_protein: RBFOX2
pureclip:
  bandwidth_nt: 80
  cl_motif_file: null
  high_precision_mode: false
  learn_on_chr21: true
  merge_distance_nt: 6
  use_cl_motif_covariate: false
  use_input_covariate: true
reference:
  annotation_gtf: null
  genome_fasta: data/GRCh38.primary_assembly.genome.fa/GRCh38.primary_assembly.genome.fa
reproducibility:
  min_crosslink_events_floor: 2
  min_replicates_passing: 2
  percentile_threshold: 10
resources:
  max_memory_gb: 16
  threads: 8
run_id: RBFOX2_iter_04
samples:
  input_control:
    rep1:
      bam: data/RBFOX2_K562/bam/smi_v1/ENCFF212IIR.bam
  ip:
    rep1:
      bam: data/RBFOX2_K562/bam/ip_rep1_v1/ENCFF537RYR.bam
    rep2:
      bam: data/RBFOX2_K562/bam/ip_rep2_v1/ENCFF296GDR.bam
target_protein: RBFOX2
